### ISSUE TITLE
Improvement: adopt shouldShowRequestPermissionRationale

### ISSUE THREAD

**Issue by stari4ek** [beworker/rx-android-permissions#1]
- https://developer.android.com/training/permissions/requesting.html

if user denied permissions already - we have a chance to show explanation UI.
And this is the way to honor "don't ask again".

**Comment by sergejsha** [comment]
You can check `shouldShowRequestPermissionRationale()` inside `PermissionsRequester.performRequestPermissions()` callback and either show explanation or call `requestPermissions()`. What else would you need?

**Comment by stari4ek** [comment]
ouch.
I'm really sorry.
Was checking 3 different rxpermissions projects and mixed up.

**Comment by sergejsha** [comment]
Без проблем. Привет Минску ;)
