### ISSUE TITLE
How to include it to project?

### ISSUE THREAD

**Issue by ecorteznearsoft** [beworker/rx-android-permissions#2]
Readme file doesn't say how to include the library in an android project.

**Comment by lectricas** [comment]
@ecorteznearsoft 
I think you can copy and paste RxPermissions.java class, but this is dirty I think...

**Comment by sergejsha** [comment]
@ecorteznearsoft Very late response, but still better than none. The library is not published on maven central. So you can clone it and include as a source android library module to your project.
